name: micrograd
channels:
        - pytorch
        - conda-forge
        - bioconda
dependencies:

        - jupyterlab_widgets
        - ipywidgets
        - ipykernel 
        - jupyterlab
        - python=3.9

        - matplotlib
        - pandas
        - numpy

        - pytorch

        # graphviz
        - graphviz
        - python-graphviz 
        - pydot



